### ISSUE TITLE
Can't see information about issues and total, passed, failed etc. number of tests

### ISSUE THREAD

**Issue by kat220** [PeterNgTr/codeceptjs-rphelper#14]
Hi,
In RP I can see passed/failed statuses only for the steps (the last window in launch). On the launch window and inside the launch I can't see any statistics, no information about total, passed, failed tests etc. Can't add an issue type.
![no_info_about_tests_issues1](https://user-images.githubusercontent.com/60749961/77366587-5ac3da80-6d69-11ea-8ad0-2c34d5eda069.png)
![no_info_abput_tests_issues](https://user-images.githubusercontent.com/60749961/77366591-5c8d9e00-6d69-11ea-9845-446e02b9bde8.png)

I use codeceptjs framework with bdd (feature) style.
Run tests:
`npx codeceptjs run --steps`
or `codeceptjs run-workers --suites 1`

**Comment by PeterNgTr** [comment]
That’s due to nested step introduced in v2.0.0. To use the legacy, try this version https://www.npmjs.com/package/codeceptjs-rphelper/v/1.1.12

**Comment by kat220** [comment]
If I use version 1.1.12 I have an error: 
```
Could not load plugin ReportPortalHelper from module 'codeceptjs-rphelper':
Class constructor ReportPortalHelper cannot be invoked without 'new'
```

stacktrace:
Error: 
```
    at createPlugins (.../node_modules/codeceptjs/lib/container.js:275:13)
    at Function.create (.../node_modules/codeceptjs/lib/container.js:45:25)
    at Codecept.init (.../node_modules/codeceptjs/lib/codecept.js:57:15)
    at Command.module.exports (.../node_modules/codeceptjs/lib/command/run.js:26:14)
    at Command.listener (.../node_modules/commander/index.js:315:8)
    at Command.emit (events.js:316:20)
    at Command.parseArgs (.../node_modules/commander/index.js:651:12)
    at Command.parse (.../node_modules/commander/index.js:474:21)
    at Object.<anonymous> (.../node_modules/codeceptjs/bin/codecept.js:228:9)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
```

**Comment by PeterNgTr** [comment]
@kat220 Please follow the readme in https://www.npmjs.com/package/codeceptjs-rphelper/v/1.1.12

the legacy version is as helper not plugin. :)

**Comment by kat220** [comment]
Sorry, my bad. It works, thanks!
Hope, it will be work with the nested steps as well :)
