### ISSUE TITLE
launch is not marked as finished

### ISSUE THREAD

**Issue by Guria** [PeterNgTr/codeceptjs-rphelper#16]
```
  "dependencies": {
    "codeceptjs": "^2.6.1",
    "codeceptjs-chai": "^1.1.0",
    "codeceptjs-rphelper": "^2.0.4",
    "pascal-case": "^3.1.1",
    "puppeteer": "^2.1.1"
  }
```
```
    reportportal: {
      require: 'codeceptjs-rphelper',
      token: 'token',
      endpoint: 'https://reportportal/api/v1',
      launchName: 'This is awesome',
      launchDescription: 'This is a description of your launch',
      launchAttributes: [{ key: 'yourKey', value: 'yourValue' }],
      projectName: 'projectl',
      rerun: false,
      debug: true,
      enabled: true
    }
```
After my test run is finished launch on reportportal not getting marked as finished.
![image](https://user-images.githubusercontent.com/36270/79050856-e2e92180-7c3d-11ea-9b77-86ff100658b9.png)

**Comment by PeterNgTr** [comment]
Any errors you see in the console logs?

**Comment by Guria** [comment]
No errors. All steps in test cases are logged correctly.
```
$ codeceptjs run --steps --grep '/^((?!(@skip|@dev)).)*$/'
creating output directory: ***
    Emitted | global.before ([object Object])
Start launch gsiwjk8vxdb6k
    gsiwjk8vxdb6k: The launchId is started.
CodeceptJS v2.6.1

/* Truncated here for privacy reason. No errors here */

  OK  | 4 passed   // 2m
◉ Step-by-step preview: **/codecept/output/records.html
Success finish item gsiwjk8vxfz8g
Finish test item gsiwjk8vxfpin
Finish test item gsiwjk8vxfpin
Success finish item gsiwjk8vxfpin
Finish test item gsiwjk8vxfpil
Success finish item gsiwjk8vxfpin
Success finish item gsiwjk8vxfpil
Done in 129.87s.
```

**Comment by PeterNgTr** [comment]
Can you run with —verbose mode to see more details if the finishLaunch is called?

**Comment by Guria** [comment]
![image](https://user-images.githubusercontent.com/36270/79053819-4597e880-7c51-11ea-91f7-28042e8c1b59.png)
There is in beginning:
```
Start launch gsi6zk8w1ywj8
    gsi6zk8w1ywj8: The launchId is started.
```
There are plenty of :
```
Start test item
Success start item
Finish test item
Success finish item
```
There is nothing about launch at the end.

**Comment by Guria** [comment]
Just ran only 1 specific test and now I have finish launch in log.
Any suggestions how I can debug that?

**Comment by Guria** [comment]
It doesn't depend on exact test. If I run just one test, no matter which, launch finishes successfully

**Comment by Guria** [comment]
In feature file with several scenario are working fine. Problem starts with at least 2 feature files.

**Comment by PeterNgTr** [comment]
Are you running with run-workers or run-multiple command?

**Comment by Guria** [comment]
No, just regular `run` command. As can ve seen in above snippet

**Comment by PeterNgTr** [comment]
Hmm. I think due to the asynchronous, some items are not closed that leads to the launch is not closed at the end.

**Comment by Guria** [comment]
I'd think that it might be caused by some of tests, but they are very basic.
And based on experiments it doesn't depend on some particular test but only depends on test files in launch.
Maybe it may depend on particular setup, eg versions and plugins enabled.
Can you provide any suggestions how it is better to debug this situation?
Can we try to add one more feature file in [your tests](https://github.com/PeterNgTr/codeceptjs-rphelper/tree/master/test/features)?

**Comment by Guria** [comment]
Can it be because of missing 'event.suite.after' listener?

I also have a few questions after reading the source:
`stepInfo` is checked in `event.all.result` handler, but it never assigned 
`beforeSuiteStatus` is only set to `'PASSED'` in `event.suite.before`.

**Comment by kobenguyent** [comment]
@Guria try with this https://github.com/reportportal/agent-js-codecept. :)

**Comment by chrismcv** [comment]
@PeterNgTr  - I'm seeing similar issues.
![image](https://user-images.githubusercontent.com/145466/108244884-99177480-7147-11eb-89b7-05db5fc1e822.png)
and errors like 
```   at /test/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:457:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 132)
(node:52) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:52) UnhandledPromiseRejectionWarning: Error: Item "40599u1gkl735tuk" not found
    at RPClient.finishTestItem (/test/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:508:53)
    at finishStep (/test/node_modules/@reportportal/agent-js-codecept/index.js:336:21)
    at startMetaSteps (/test/node_modules/@reportportal/agent-js-codecept/index.js:301:13)
    at /test/node_modules/@reportportal/agent-js-codecept/index.js:125:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 133)
  ✔ Write of Ledger code @Settings @Finances @C50657 in 111476ms
(node:52) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at /test/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:457:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 134)
(node:52) UnhandledPromiseRejectionWarning: Error: Item "40599u1gkl738dsm" not found
    at RPClient.finishTestItem (/test/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:508:53)
    at finishStep (/test/node_modules/@reportportal/agent-js-codecept/index.js:336:21)
    at startMetaSteps (/test/node_modules/@reportportal/agent-js-codecept/index.js:301:13)
    at /test/node_modules/@reportportal/agent-js-codecept/index.js:125:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 135)
  ✔ Discount Ledger Code @Settings @Finances @C50658 in 125348ms
(node:52) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'realId' of undefined
    at /test/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:457:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 136)
(node:52) UnhandledPromiseRejectionWarning: Error: Item "40599u1gkl73b7rc" not found
    at RPClient.finishTestItem (/test/node_modules/@reportportal/client-javascript/lib/report-portal-client.js:508:53)
    at finishStep (/test/node_modules/@reportportal/agent-js-codecept/index.js:336:21)
    at startMetaSteps (/test/node_modules/@reportportal/agent-js-codecept/index.js:301:13)
    at /test/node_modules/@reportportal/agent-js-codecept/index.js:125:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    ```
